<?php

declare(strict_types=1);

namespace Token27\NexusAI\Response;

use Token27\NexusAI\Contract\ResponseInterface;
use Token27\NexusAI\Enum\FinishReason;
use Token27\NexusAI\Message\Message;
use Token27\NexusAI\Pricing\Contract\PricingResultInterface;
use Token27\NexusAI\Pricing\ValueObject\Usage;
use Token27\NexusAI\ValueObject\Meta;
use Token27\NexusAI\ValueObject\ToolCall;

/**
 * Result of a chat completion request.
 *
 * Contains the generated text, metadata, and optionally the full conversation
 * history including multi-step tool calling interactions.
 *
 * Inspired by Prism's Text\Response (readonly class with text, finishReason,
 * toolCalls, usage, meta, steps, messages, response).
 *
 * @see \Token27\NexusAI\Contract\DriverInterface::text()
 * @see \Token27\NexusAI\Request\TextRequest
 */
final readonly class TextResponse implements ResponseInterface
{
    /**
     * @param string $text Text generated by the LLM.
     * @param FinishReason $finishReason Reason why the LLM stopped generating.
     * @param array<ToolCall> $toolCalls Tool calls from the last step. Empty if none.
     * @param Usage $usage Total token usage (sum of all steps).
     * @param Meta $meta Response metadata (ID, model, rate limits).
     * @param array<self> $steps History of steps for multi-step tool calling. Each step is a partial TextResponse.
     * @param array<Message> $messages Complete conversation including tool calls and results.
     * @param array<string, mixed>|null $raw Raw JSON response from the last HTTP request. For debugging.
     * @param PricingResultInterface|null $pricingResult Calculated pricing result when pricing middleware is active.
     */
    public function __construct(
        public string $text,
        public FinishReason $finishReason,
        public array $toolCalls = [],
        public Usage $usage = new Usage(),
        public Meta $meta = new Meta(),
        public array $steps = [],
        public array $messages = [],
        public ?array $raw = null,
        public ?PricingResultInterface $pricingResult = null,
    ) {
    }

    public function withPricingResult(PricingResultInterface $pricingResult): self
    {
        return new self(
            text: $this->text,
            finishReason: $this->finishReason,
            toolCalls: $this->toolCalls,
            usage: $this->usage,
            meta: $this->meta,
            steps: $this->steps,
            messages: $this->messages,
            raw: $this->raw,
            pricingResult: $pricingResult,
        );
    }

    /** {@inheritdoc} */
    public function getUsage(): Usage
    {
        return $this->usage;
    }

    /** {@inheritdoc} */
    public function getMeta(): Meta
    {
        return $this->meta;
    }

    /** {@inheritdoc} */
    public function getFinishReason(): FinishReason
    {
        return $this->finishReason;
    }

    /** {@inheritdoc} */
    public function getRaw(): ?array
    {
        return $this->raw;
    }
}
