<?php

declare(strict_types=1);

namespace Token27\NexusAI\ValueObject;

/**
 * Represents a tool invocation requested by the LLM.
 *
 * When the LLM wants to call a tool, it returns one or more ToolCall objects.
 * The callId is used to correlate with the corresponding ToolResult.
 *
 * @see \Token27\NexusAI\ValueObject\ToolResult
 * @see \Token27\NexusAI\Message\ToolCallMessage
 */
readonly class ToolCall
{
    /**
     * @param string $id Unique ID generated by the provider (e.g., 'call_abc123'). Used to correlate with ToolResult.
     * @param string $name Name of the tool to invoke (e.g., 'get_weather').
     * @param array<string, mixed> $arguments Parsed arguments from the LLM's JSON (e.g., ['city' => 'Madrid', 'units' => 'celsius']).
     */
    public function __construct(
        public string $id,
        public string $name,
        public array $arguments,
    ) {
    }
}
